version: "3.7"

services:
  composer:
    build:
      context: .
      dockerfile: Playground-Dockerfile
    container_name: composer
    restart: always
    volumes:
      - ~/.composer:/home/composer/.composer
    ports:
      - "8080:8080"

  cp_rest_api:
    build:
      context: .
      dockerfile: REST-Server-Dockerfile
    container_name: cp_rest_api
    restart: always
    environment:
      - COMPOSER_CARD=CP@digid
      - COMPOSER_NAMESPACES=never
    volumes:
      - ~/.composer:/home/composer/.composer
    ports:
      - "${cp_dlt_port}:3000"
    depends_on:
      - composer

  ap_rest_api:
    build:
      context: .
      dockerfile: REST-Server-Dockerfile
    container_name: ap_rest_api
    restart: always
    environment:
      - COMPOSER_CARD=AP@digid
      - COMPOSER_NAMESPACES=never
    volumes:
      - ~/.composer:/home/composer/.composer
    ports:
      - "${ap_dlt_port}:3000"
    depends_on:
      - composer

  cp:
    build: ./cp
    container_name: cp
    restart: always
    environment:
      - APP_NAME=CertificationProvider
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "${cp_port}:5000"

  ap:
    build: ./ap
    container_name: ap
    restart: always
    environment:
      - APP_NAME=AuthenticationProvider
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "${ap_port}:5000"

  service:
    build: ./service
    container_name: service
    restart: always
    environment:
      - APP_NAME=Service
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "${service_port}:5000"

  user:
    build: ./user
    container_name: user
    restart: always
    environment:
      - APP_NAME=User
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "${user_port}:5000"

#  nginx:
#    build: ./nginx
#    container_name: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "${user_port}:${user_port}"
#      - "${ap_port}:${ap_port}"
#      - "${cp_port}:${cp_port}"
#      - "${service_port}:${service_port}"
#      - "${ap_dlt_port}:3000"
#      - "${cp_dlt_port}:3000"
#    depends_on:
#      - user
#      - service
#      - cp
#      - ap
#      - cp_rest_api
#      - ap_rest_api
#      - composer

networks:
  default:
    external:
      name: composer_default
